#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 satoimotaro
"""Generate the firmware's C++ speed-profile header from the calibrated YAML profiles.

The YAML velcal profiles in host/profiles/ are the SINGLE SOURCE OF TRUTH for a motor's
thrust<->mech-RPM curve, its sine<->6-step crossover, its capabilities, and its closed-loop PI gains.
This tool emits a matching `vel::SpeedProfile` (+ regimes, crossover, and a `vel::Gains`) per motor
into src/apps/profiles_gen.h, so the firmware never carries hand-typed curve numbers that can drift
from the calibration.

Usage:
    python3 gen_profile_header.py                       # all host/profiles/vel_*.yaml -> profiles_gen.h
    python3 gen_profile_header.py a.yaml b.yaml -o out.h
    python3 gen_profile_header.py --check               # fail (non-zero) if profiles_gen.h is stale
"""
from __future__ import annotations

import argparse
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pico_esc.velocity import SpeedProfile  # noqa: E402

HOST = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT = os.path.normpath(os.path.join(HOST, "..", "src", "apps", "profiles_gen.h"))
DEFAULT_GLOB = os.path.join(HOST, "profiles", "vel_*.yaml")
_REGIME = {"sine": "vel::Regime::SINE", "line": "vel::Regime::LINE"}


def _cident(path: str) -> str:
    """A C identifier SUFFIX from the FILENAME (so bench/sim/6step of one motor don't collide): a
    leading `vel_` is dropped, then upper + non-alnum -> _. e.g. vel_930kv_12n14p_6step -> 930KV_12N14P_6STEP."""
    stem = os.path.splitext(os.path.basename(path))[0]
    if stem.startswith("vel_"):
        stem = stem[4:]
    ident = re.sub(r"[^0-9A-Za-z]+", "_", stem).strip("_").upper()
    return ident or "PROFILE"


def _f(x: float) -> str:
    # Always a float literal: `2576f` is an error (f-suffix on an integer constant), so ensure a '.'.
    s = f"{x:g}"
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


def _emit_one(p: SpeedProfile, path: str) -> str:
    n = _cident(path)
    rows = ", ".join("{%s, %s}" % (_f(t), _f(r)) for t, r in p.points)
    out = [f"// --- {p.motor or n}  (from {os.path.basename(path)}) ---",
           f"static const vel::CurvePoint CURVE_{n}[] = {{ {rows} }};"]

    regimes_arg = "nullptr"
    if p.regimes is not None and all(r in _REGIME for r in p.regimes):
        vals = ", ".join(_REGIME[r] for r in p.regimes)
        out.append(f"static const vel::Regime CURVE_{n}_REGIMES[] = {{ {vals} }};")
        regimes_arg = f"CURVE_{n}_REGIMES"

    cx_arg = "nullptr"
    if p.crossover and p.crossover.get("up_erpm") is not None:
        up, dn = p.crossover.get("up_erpm"), p.crossover.get("dn_erpm", 0.0)
        out.append(f"static const vel::Crossover CROSSOVER_{n} = {{ {_f(up)}, {_f(dn or 0.0)} }};")
        cx_arg = f"&CROSSOVER_{n}"

    down_catch = "true" if (p.capabilities and p.capabilities.get("down_catch")) else "false"
    count = len(p.points)
    out.append(
        f"static const vel::SpeedProfile M_{n}(\n"
        f"\tCURVE_{n}, {count}, /*pole_pairs=*/{p.pole_pairs}, {cx_arg}, {regimes_arg}, {down_catch});")

    if p.control:
        g = p.control
        out.append("static const vel::Gains M_%s_GAINS = { %s, %s, %s, %s };" % (
            n, _f(g.get("kp", 0.4)), _f(g.get("ki", 1.5)),
            _f(g.get("trim_max", 200.0)), _f(g.get("blend_secs", 0.3))))
    return "\n".join(out)


def generate(paths: list[str]) -> str:
    blocks = []
    for path in sorted(paths):
        p = SpeedProfile.load(path)
        blocks.append(_emit_one(p, path))
    body = "\n\n".join(blocks)
    rel = [os.path.relpath(p, HOST) for p in sorted(paths)]
    return (
        "// SPDX-License-Identifier: GPL-3.0-or-later\n"
        "// Copyright (C) 2026 satoimotaro\n"
        "//\n"
        "// profiles_gen — GENERATED by host/gen_profile_header.py. DO NOT EDIT BY HAND.\n"
        "// Each vel::SpeedProfile / vel::Gains here is emitted from a calibrated YAML in host/profiles/\n"
        "// (the single source of truth). Regenerate after a velcal:  python3 host/gen_profile_header.py\n"
        f"// Sources: {', '.join(rel)}\n"
        "#pragma once\n"
        '#include "vel_control.h"\n\n'
        "namespace profiles {\n\n"
        f"{body}\n\n"
        "}  // namespace profiles\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("inputs", nargs="*", help="profile YAMLs (default: host/profiles/vel_*.yaml)")
    ap.add_argument("-o", "--out", default=DEFAULT_OUT, help=f"output header (default: {DEFAULT_OUT})")
    ap.add_argument("--check", action="store_true",
                    help="don't write; exit non-zero if the on-disk header differs (CI / pre-commit)")
    opts = ap.parse_args()

    paths = opts.inputs or sorted(glob.glob(DEFAULT_GLOB))
    if not paths:
        sys.exit("no profile YAMLs found")
    text = generate(paths)

    if opts.check:
        cur = open(opts.out, encoding="utf-8").read() if os.path.exists(opts.out) else None
        if cur != text:
            print(f"STALE: {opts.out} is out of date — run: python3 host/gen_profile_header.py")
            return 1
        print(f"OK: {opts.out} is up to date ({len(paths)} profile(s))")
        return 0

    with open(opts.out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {opts.out} from {len(paths)} profile(s): {', '.join(os.path.basename(p) for p in paths)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
