// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 satoimotaro
//
// profiles_gen — GENERATED by host/gen_profile_header.py. DO NOT EDIT BY HAND.
// Each vel::SpeedProfile / vel::Gains here is emitted from a calibrated YAML in host/profiles/
// (the single source of truth). Regenerate after a velcal:  python3 host/gen_profile_header.py
// Sources: profiles/vel_930kv_12n14p_6step.yaml, profiles/vel_930kv_12n14p_bench.yaml, profiles/vel_930kv_12n14p_sim.yaml, profiles/vel_930kv_sineoff.yaml
#pragma once
#include "vel_control.h"

namespace profiles {

// --- 930kv_12n14p  (from vel_930kv_12n14p_6step.yaml) ---
static const vel::CurvePoint CURVE_930KV_12N14P_6STEP[] = { {0.0f, 0.0f}, {60.0f, 20.3f}, {108.0f, 35.6f}, {155.0f, 51.8f}, {202.0f, 67.6f}, {250.0f, 83.6f}, {620.0f, 2576.0f}, {700.0f, 4645.0f}, {800.0f, 7173.0f}, {900.0f, 9447.0f}, {1000.0f, 11000.0f} };
static const vel::Regime CURVE_930KV_12N14P_6STEP_REGIMES[] = { vel::Regime::SINE, vel::Regime::SINE, vel::Regime::SINE, vel::Regime::SINE, vel::Regime::SINE, vel::Regime::SINE, vel::Regime::LINE, vel::Regime::LINE, vel::Regime::LINE, vel::Regime::LINE, vel::Regime::LINE };
static const vel::Crossover CROSSOVER_930KV_12N14P_6STEP = { 1500.0f, 1350.0f };
static const vel::SpeedProfile M_930KV_12N14P_6STEP(
	CURVE_930KV_12N14P_6STEP, 11, /*pole_pairs=*/7, &CROSSOVER_930KV_12N14P_6STEP, CURVE_930KV_12N14P_6STEP_REGIMES, false);
static const vel::Gains M_930KV_12N14P_6STEP_GAINS = { 0.03f, 0.12f, 400.0f, 0.3f };

// --- 930kv_12n14p  (from vel_930kv_12n14p_bench.yaml) ---
static const vel::CurvePoint CURVE_930KV_12N14P_BENCH[] = { {0.0f, 0.0f}, {60.0f, 20.27f}, {108.0f, 35.57f}, {155.0f, 51.76f}, {202.0f, 67.63f}, {250.0f, 83.55f} };
static const vel::SpeedProfile M_930KV_12N14P_BENCH(
	CURVE_930KV_12N14P_BENCH, 6, /*pole_pairs=*/7, nullptr, nullptr, false);
static const vel::Gains M_930KV_12N14P_BENCH_GAINS = { 0.03f, 0.12f, 400.0f, 0.3f };

// --- 930kv_12n14p  (from vel_930kv_12n14p_sim.yaml) ---
static const vel::CurvePoint CURVE_930KV_12N14P_SIM[] = { {0.0f, 0.0f}, {50.0f, 17.67f}, {136.0f, 48.19f}, {223.0f, 80.09f}, {309.0f, 109.75f}, {395.0f, 141.73f}, {482.0f, 171.19f}, {568.0f, 202.37f}, {655.0f, 235.46f}, {741.0f, 263.97f}, {827.0f, 295.13f}, {914.0f, 712.1f}, {1000.0f, 783.13f} };
static const vel::Regime CURVE_930KV_12N14P_SIM_REGIMES[] = { vel::Regime::SINE, vel::Regime::SINE, vel::Regime::SINE, vel::Regime::SINE, vel::Regime::SINE, vel::Regime::SINE, vel::Regime::SINE, vel::Regime::SINE, vel::Regime::SINE, vel::Regime::SINE, vel::Regime::SINE, vel::Regime::LINE, vel::Regime::LINE };
static const vel::Crossover CROSSOVER_930KV_12N14P_SIM = { 2100.0f, 1600.0f };
static const vel::SpeedProfile M_930KV_12N14P_SIM(
	CURVE_930KV_12N14P_SIM, 13, /*pole_pairs=*/7, &CROSSOVER_930KV_12N14P_SIM, CURVE_930KV_12N14P_SIM_REGIMES, false);

// --- 930kv_12n14p_sineoff  (from vel_930kv_sineoff.yaml) ---
static const vel::CurvePoint CURVE_930KV_SINEOFF[] = { {0.0f, 0.0f}, {620.0f, 2576.0f}, {700.0f, 4645.0f}, {800.0f, 7173.0f}, {900.0f, 9447.0f}, {1000.0f, 11000.0f} };
static const vel::SpeedProfile M_930KV_SINEOFF(
	CURVE_930KV_SINEOFF, 6, /*pole_pairs=*/7, nullptr, nullptr, false);
static const vel::Gains M_930KV_SINEOFF_GAINS = { 0.03f, 0.12f, 400.0f, 0.3f };

}  // namespace profiles
